[package]
name = "glove80-control-surface"
description = "Cross-platform desktop application for the Glove80 control surface"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "glove80_control_surface_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
control-core = { path = "../../../crates/control-core" }
serde.workspace = true
surface-protocol = { path = "../../../crates/surface-protocol" }
tauri = { version = "2.11.5", features = [] }
